name: Deploy to production
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: yarn
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: "cd /var/www/halo-client && git pull && cd /var/www/laradock && docker-compose exec -T workspace bash -c 'cd /var/www/halo-client/ && sh .scripts/deploy.sh'"
